### PR TITLE
Some suggested code-style changes

### PR DESCRIPTION
**Pull request by nottrobin**
- PEP8 fixes
- Add README.md and requirements.txt
- Do the argparse and data handling stuff slightly more elegantly (I hope)

For more information, read the individual commits. Especially the first one
about PEP8.

### CODE REVIEW

**Comment by anthonydillon** [comment]
What is the status of this PR?

**Comment by nottrobin** [comment]
it's for @femma to look at if she has time. @femma should I just close it?

**Comment by deadlight** [comment]
@femma ?

**Review by anthonydillon — APPROVED** [review]
Much better, thanks.

**Pull request merged**
